name: Hu_custom
version: '${project.version}'
main: me.hu_custom.Main
api-version: 1.18
commands:
  Resource:
    aliases:
      - urlt
  Slime:
    aliases:
      - smp
  Item_get:
    aliases:
      - huget

