name: Hu_custom
version: '${project.version}'
main: me.hu_custom.Main
api-version: 1.18
authors:
  - WEIWEI
commands:
  equipment_roll:
    aliases:
      - equipment_roll
  Resource:
    aliases:
      - urlt
  Slime:
    aliases:
      - smp
  Item_get:
    aliases:
      - huget
  mry:
    aliases:
      - mry
  chequemoney:
    aliases:
      - chequemoney
  chequeexp:
    aliases:
      - chequeexp
  chequehub:
    aliases:
      - chequehub
  bind:
    aliases:
      - bind
  unbind:
    aliases:
      - unbind
  dr:
    aliases:
      - dr
  bosstime:
    aliases:
    - bosstime
  taxcheck:
    aliases:
      - taxcheck
  sxbagkey:
    aliases:
      - sxbagkey
  buffmenu:
    aliases:
      - buffmenu
  cmd_playerlist:
    aliases:
      - cmd_playerlist
  autosell:
    aliases:
      - autosell


